#ifndef PIC_EXCEPTIONS_HPP
#define PIC_EXCEPTIONS_HPP

#include "Utilities/ExceptionMacros.hpp"

START_DEFINE_EXCEPTION(PICBaseException, std::runtime_error)
START_DEFINE_EXCEPTION(PICParticleDynamicsProcessorStdVersionHelperException, PICBaseException)
START_DEFINE_EXCEPTION(PICParticleDynamicsProcessorOmpVersionHelperException, PICBaseException)
START_DEFINE_EXCEPTION(PICParticleDynamicsProcessorOmpVersionHelperUnknownException, PICBaseException)
START_DEFINE_EXCEPTION(PICParticleDynamicsProcessorOmpVersionProcessingException, PICBaseException)
START_DEFINE_EXCEPTION(PICParticleDynamicsProcessorStdVersionProcessingException, PICBaseException)
START_DEFINE_EXCEPTION(PICParticleDynamicsProcessorProcessingException, PICBaseException)

START_DEFINE_EXCEPTION(PICChargeDensityEquationSolverSolvingException, PICBaseException)
START_DEFINE_EXCEPTION(PICChargeDensityEquationSolverUnknownException, PICBaseException)

START_DEFINE_EXCEPTION(PICNodeChargeDensityProcessorStdVersionHelperException, PICBaseException)
START_DEFINE_EXCEPTION(PICNodeChargeDensityProcessorOmpVersionHelperException, PICBaseException)
START_DEFINE_EXCEPTION(PICNodeChargeDensityProcessorOmpVersionHelperUnknownException, PICBaseException)
START_DEFINE_EXCEPTION(PICNodeChargeDensityProcessorStdVersionHelperUnknownException, PICBaseException)

#endif // !PIC_EXCEPTIONS_HPP
