#ifndef PIC_EXCEPTIONS_HPP
#define PIC_EXCEPTIONS_HPP

#include "Utilities/ExceptionMacros.hpp"

START_DEFINE_EXCEPTION(PICBaseException, std::runtime_error)
START_DEFINE_EXCEPTION(PICBaseIosBaseFailureException, std::ios_base::failure)
START_DEFINE_EXCEPTION(PICUnknownException, PICBaseException)

START_DEFINE_EXCEPTION(PICParticleDynamicsProcessorStdVersionHelperException, PICBaseException)
START_DEFINE_EXCEPTION(PICParticleDynamicsProcessorOmpVersionHelperException, PICBaseException)
START_DEFINE_EXCEPTION(PICParticleDynamicsProcessorOmpVersionHelperUnknownException, PICUnknownException)
START_DEFINE_EXCEPTION(PICParticleDynamicsProcessorOmpVersionProcessingException, PICBaseException)
START_DEFINE_EXCEPTION(PICParticleDynamicsProcessorStdVersionProcessingException, PICBaseException)
START_DEFINE_EXCEPTION(PICParticleDynamicsProcessorProcessingException, PICBaseException)

START_DEFINE_EXCEPTION(PICChargeDensityEquationSolverSolvingException, PICBaseException)
START_DEFINE_EXCEPTION(PICChargeDensityEquationSolverUnknownException, PICUnknownException)

START_DEFINE_EXCEPTION(PICNodeChargeDensityProcessorStdVersionHelperException, PICBaseException)
START_DEFINE_EXCEPTION(PICNodeChargeDensityProcessorOmpVersionHelperException, PICBaseException)
START_DEFINE_EXCEPTION(PICNodeChargeDensityProcessorOmpVersionHelperUnknownException, PICUnknownException)
START_DEFINE_EXCEPTION(PICNodeChargeDensityProcessorStdVersionHelperUnknownException, PICUnknownException)

START_DEFINE_EXCEPTION(PICParticleMovementTrackerException, PICBaseException)
START_DEFINE_EXCEPTION(PICParticleMovementTrackerUnknownException, PICUnknownException)
START_DEFINE_EXCEPTION(PICParticleMovementTrackerSaveMovementsToJsonException, PICBaseIosBaseFailureException)

#endif // !PIC_EXCEPTIONS_HPP
