#ifndef GMSH_UTILS_EXCEPTIONS_HPP
#define GMSH_UTILS_EXCEPTIONS_HPP

#include "Utilities/ExceptionMacros.hpp"

START_DEFINE_EXCEPTION(GmshUtilsBaseException, std::runtime_error)
START_DEFINE_EXCEPTION(GmshUtilsGmshNotInitializedException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsFileDoesNotExistException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsFileIsDirectoryException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsFileExtensionIsNotMshException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsFileIsEmptyException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsNoVolumeEntitiesException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsNoBoundaryTagsException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsNoNodeTagsException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsNoTriangleCellsException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsFailedToFillTriangleNodeTagsMapException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsFailedToFillTriangleCentersMapException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsFailedToFillCellsMapException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsNoPhysicalGroupsException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsPhysicalGroupNotFoundException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsNoSurfaceCoordsException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsInvalidSurfaceCoordsException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsFailedToFillTriangleCellsMapException, GmshUtilsBaseException)
START_DEFINE_EXCEPTION(GmshUtilsFailedToCreateTriangleException, GmshUtilsBaseException)

#endif // !GMSH_UTILS_EXCEPTIONS_HPP
