#ifndef TRIANGLE_MESH_HDF5_MANAGER_EXCEPTIONS_HPP
#define TRIANGLE_MESH_HDF5_MANAGER_EXCEPTIONS_HPP

#include "Utilities/ExceptionMacros.hpp"

START_DEFINE_EXCEPTION(DataHandlingBaseException, std::runtime_error)
START_DEFINE_EXCEPTION(DataHandlingUnknownException, DataHandlingBaseException)

START_DEFINE_EXCEPTION(TriangleMeshHdf5ManagerInputParameterEmptyException, DataHandlingBaseException)
START_DEFINE_EXCEPTION(TriangleMeshHdf5ManagerFailedToFindMinimumIdException, DataHandlingBaseException)
START_DEFINE_EXCEPTION(TriangleMeshHdf5ManagerFailedToCreateHdf5FileException, DataHandlingBaseException)
START_DEFINE_EXCEPTION(TriangleMeshHdf5ManagerFailedToCreateGroupException, DataHandlingBaseException)
START_DEFINE_EXCEPTION(TriangleMeshHdf5ManagerFailedToCreateDatasetException, DataHandlingBaseException)
START_DEFINE_EXCEPTION(TriangleMeshHdf5ManagerFailedToOpenDatasetException, DataHandlingBaseException)

#endif // !TRIANGLE_MESH_HDF5_MANAGER_EXCEPTIONS_HPP
