#ifndef TRIANGLE_MESH_HDF5_MANAGER_EXCEPTIONS_HPP
#define TRIANGLE_MESH_HDF5_MANAGER_EXCEPTIONS_HPP

#include "Utilities/ExceptionMacros.hpp"

START_DEFINE_EXCEPTION(TriangleMeshHdf5ManagerBaseException, std::runtime_error)
START_DEFINE_EXCEPTION(TriangleMeshHdf5ManagerInputParameterEmptyException, TriangleMeshHdf5ManagerBaseException)
START_DEFINE_EXCEPTION(TriangleMeshHdf5ManagerFailedToFindMinimumIdException, TriangleMeshHdf5ManagerBaseException)
START_DEFINE_EXCEPTION(TriangleMeshHdf5ManagerFailedToCreateHdf5FileException, TriangleMeshHdf5ManagerBaseException)
START_DEFINE_EXCEPTION(TriangleMeshHdf5ManagerFailedToCreateGroupException, TriangleMeshHdf5ManagerBaseException)
START_DEFINE_EXCEPTION(TriangleMeshHdf5ManagerFailedToCreateDatasetException, TriangleMeshHdf5ManagerBaseException)
START_DEFINE_EXCEPTION(TriangleMeshHdf5ManagerFailedToOpenDatasetException, TriangleMeshHdf5ManagerBaseException)

#endif // !TRIANGLE_MESH_HDF5_MANAGER_EXCEPTIONS_HPP
