name: Run Python Tests

on:
  push:
    branches: [main, develop]
    paths:
      - "**/*.py"
  pull_request:
    branches: [main, develop]
    paths:
      - "**/*.py"
  workflow_dispatch:

jobs:
  run_python_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.7
        uses: actions/setup-python@v5
        with:
          python-version: 3.7
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libglu1-mesa libgl1 ffmpeg libsm6 libxext6 libxft-dev libxinerama-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python tests
        run: |
          python ui/run_tests.py
